CREATE TABLE USERS(
    USER_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(200),
    EMAIL TEXT,
    PASSWORD VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE INDEX ix_users ON USERS (
    USER_ID,
    EMAIL(10)
);

COMMIT;