CREATE TABLE USERS(
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(200),
    EMAIL TEXT,
    PASSWORD VARCHAR(200),
);

ALTER TABLE USERS ADD PRIMARY KEY (USER_ID);

CREATE INDEX ON USERS (
    USER_ID,
    EMAIL
);

COMMIT;